# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Playwright tests
on: [push]

jobs:
  build:
    name: Run Playwright Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Playwright from 'npm' and Run Tests
      - uses: microsoft/playwright-github-action@v1.2.0
        with:
          args: "node src/tests/test.js"